### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by kafku** [kafku/RcppFire#1]
TODO
- [ ] edit configure.ac
  - [x] build test for gcc
  - [ ] build test for clang
  - [ ] build test for icpc
- [ ] add `Exporter` class specialized for `af::array`
- [ ] fix RcppFire.package.skelton
- [ ] update DESCRIPTION
- [ ] add documentation
- [ ] add test code
- [ ] add files for package skelton
